### PR TITLE
Add dataset example Hugo_CATI

### PR DESCRIPTION
**Pull request by Hboni**
I tried to create a BIDS hierarchy for our main PET preprocess pipeline at CATI, named AMETHYST. Nifti files are empty files, as it focuses more on organization, to avoid issues sharing not defaced imaging data publically.

In this example, I did not detail JSON for MRI preprocessing, nor "rois" preprocessing.

I do not know how to handle transformation files, I saw that some discussions were started in a BEP, but I was not sure how to do it in my case. As this is more focus on PET data, I thought it unnecessary.

### CODE REVIEW

**Comment by mnoergaard** [comment]
This is great! Thank you @Hboni

**Comment by Hboni** [comment]
@mnoergaard  After looking back to what I pushed, I was making some adjustments to simplify some parts. If it is ok, I will push that updates on the main project :wink:

**Comment by mnoergaard** [comment]
Of course! Feel free to update all you want. Looking forward to discuss these efforts tomorrow!

**Comment by Hboni** [comment]
It seems that I don't have permissions to push on openneuropet/pet-bids-derivatives-data

```
remote: Permission to openneuropet/pet-bids-derivatives-data.git denied to Hboni.
```

**Comment by mnoergaard** [comment]
@Hboni you should have received an invite to become a collaborator on this with write access

**Comment by Hboni** [comment]
Yes, I received the invitation and I pushed my modifications. Thanks!

**Pull request merged**
